apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "project-management-api.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USER: {{ .Values.DATABASE_USER | b64enc }}
  DATABASE_PASSWORD: {{ .Values.DATABASE_PASSWORD | b64enc }}
  REDIS_PASSWORD: {{ .Values.REDIS_PASSWORD | b64enc }}
  NATS_USERNAME: {{ .Values.NATS_USERNAME | b64enc }}
  NATS_PASSWORD: {{ .Values.NATS_PASSWORD | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.MINIO_ACCESS_KEY | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.MINIO_SECRET_KEY | b64enc }} 
  JWT_SECRET: {{ .Values.JWT_SECRET | b64enc }}

